### ISSUE TITLE
News version

### ISSUE THREAD

**Issue by TrimVa** [verjus/Zigbee-3.0-USB-dongle-plus-firmware#1]
hello, 

could you compile the latest version? with SDK sdk_6_20_00_29? I tried it myself, but it doesn't work for me

thank you

**Comment by verjus** [comment]
@TrimVa, I will try this week-end and post it here if I succeed.

**Comment by TrimVa** [comment]
Thank you :)
--
Girard Sylvain vendredi, 07 octobre 2022, 03:37AM +02:00 de verjus  ***@***.*** :

***@***.*** , I will try this week-end and post it here if I succeed.

**Comment by verjus** [comment]
Hello @TrimVa 

I just finished compiling the latest version of Koenkk's latest firmware with HFC. You can find it [here](https://github.com/verjus/Zigbee-3.0-USB-dongle-plus-firmware/tree/main/bin_20220928_TEST)

I did not test. I just flashed to my home system and it looks like it works for me. Please let me know if it works for you.

**Comment by TrimVa** [comment]
Hello,
I will test the day at home too and let you know.  thank you :)

**Comment by TrimVa** [comment]
@verjus it also works for me with Zigbee2Mqtt on HA, thank you very much :D
